<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mindy_Demo</name>
   <tag></tag>
   <elementGuidId>934717a3-069d-4c99-82e1-655646b8f2af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='70fa2da4-0d8f-4495-b4f0-445e5ba9d82d']/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.templateTitle.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c41a51b8-65a7-4790-be6b-384129988619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>templateTitle ng-binding</value>
      <webElementGuid>1d7ee2a0-bd06-4635-97f9-6eccc26afb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>header-title</value>
      <webElementGuid>4353c6e6-f9f0-4fe2-9d4d-8b923d949a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.onTitleClick(item); $event.stopPropagation();</value>
      <webElementGuid>11142942-6baa-4471-bdfe-5b1d3b37f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mindy_Demo</value>
      <webElementGuid>180fcb46-95ec-4acb-883c-ee9fc5892d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;70fa2da4-0d8f-4495-b4f0-445e5ba9d82d&quot;)/td[@class=&quot;--extra-wide&quot;]/span[@class=&quot;templateTitle ng-binding&quot;]</value>
      <webElementGuid>9f2b7a2a-354b-44df-ac3f-61d01492e06b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='70fa2da4-0d8f-4495-b4f0-445e5ba9d82d']/td[2]/span</value>
      <webElementGuid>8a322aa6-5001-4871-bae6-a89790d6599e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modified by'])[1]/following::span[1]</value>
      <webElementGuid>63ec7e04-015d-4526-af81-d622e6785d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modified'])[1]/following::span[4]</value>
      <webElementGuid>c2d1e7d7-97d4-4bed-8270-69459bef30fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[2]/preceding::span[1]</value>
      <webElementGuid>f2901aaf-691c-404b-af10-c298983be7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mindy Kim'])[2]/preceding::span[2]</value>
      <webElementGuid>e32092e4-a05b-4480-bff7-5050c30ddf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mindy_Demo']/parent::*</value>
      <webElementGuid>ef3c2924-f745-4d57-affc-4929ae4bae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>177420c7-a9b9-4c37-a2e9-8f0ecf82061e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mindy_Demo' or . = 'Mindy_Demo')]</value>
      <webElementGuid>f98a0129-163e-47c7-8bde-1bf2ab3b5614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
