<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>0acd6547-cf91-4139-b965-298023186acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.osr-button.osr-button--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/osr-email-input/form/osr-submit-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7786c5ff-f4bc-4637-836d-85838d8906b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osr-button osr-button--primary</value>
      <webElementGuid>a06a46ce-6173-4c73-8690-2fc36b2b8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>vm.buttonClass</value>
      <webElementGuid>91903610-52bd-4a17-91f6-d9cd53a7eb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.ngDisabled</value>
      <webElementGuid>57042ece-2344-4e2d-aade-77e864a54635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>next-button</value>
      <webElementGuid>2e807ac7-62fb-4fcf-a623-1df4012ca996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>929590a2-9eb5-472a-bc98-a3601e735ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__single_spa_angular_1&quot;)/ui-view[@class=&quot;ultimate ng-scope&quot;]/div[@id=&quot;fullscreen-root-container&quot;]/div[@class=&quot;login osrFlexItem&quot;]/div[@class=&quot;osrFlex&quot;]/div[@class=&quot;widget widget_container-login-form osrFlexItem osrFlexItem__grow ng-scope&quot;]/osr-login[@class=&quot;ng-scope ng-isolate-scope&quot;]/osr-email-input[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/osr-submit-button[@class=&quot;ng-isolate-scope&quot;]/button[@class=&quot;osr-button osr-button--primary&quot;]</value>
      <webElementGuid>7f14b04f-0520-493f-84da-a6f13dd2330e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/osr-email-input/form/osr-submit-button/button</value>
      <webElementGuid>5c864bc7-c977-4c64-81fe-53b8c63c4ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>081bb55c-7d8b-4d35-ae0f-296298ae24d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[1]</value>
      <webElementGuid>780f2f8f-8c83-4850-bae6-9c9f7cfef4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//osr-submit-button/button</value>
      <webElementGuid>672c1d68-c5fc-4652-a46a-14ccabef18f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b3a0659f-f069-4104-a9c7-d2d3bd65535c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
