<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_model.Password</name>
   <tag></tag>
   <elementGuidId>b81e9ee6-ffd0-4b9d-a6b2-d38679adba74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;model.Password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='model.Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb15ca50-ecce-4612-8664-61e9fc4507d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6d0ea5b2-d52c-4d56-aac8-33192138546e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ vm.showPassword ? 'text' : 'password' }}</value>
      <webElementGuid>60c3d2b6-4d3f-42e7-a49d-80556fbbbb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model.Password</value>
      <webElementGuid>72a12f78-fabe-4e13-a059-5a84cdf96a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osr-text-box__input ng-untouched ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>60872748-eaa7-4359-9414-30d26b47ad7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.ngModel</value>
      <webElementGuid>44ed74dd-dbdb-4ac7-aa89-7cb3318b0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.onChange()</value>
      <webElementGuid>d55ce533-ba8f-4c4f-9b78-32ae262fb595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>vm.required</value>
      <webElementGuid>4177a902-254f-4ec1-9b29-b68c7dccb284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.ngDisabled</value>
      <webElementGuid>bdf3d708-f584-4685-b8ea-b05c3b6d80bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1786396f-19a7-4755-b617-eeb7ba9b9844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7748fe40-3546-4fcc-90d5-c37186a13580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-autocomplete</name>
      <type>Main</type>
      <value>{{vm.autocomplete == false ? 'off' : ''}}</value>
      <webElementGuid>164c10c2-9f5a-49dc-ad6e-b46a13b824a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__single_spa_angular_1&quot;)/ui-view[@class=&quot;ultimate ng-scope&quot;]/div[@id=&quot;fullscreen-root-container&quot;]/div[@class=&quot;login osrFlexItem&quot;]/div[@class=&quot;osrFlex&quot;]/div[@class=&quot;widget widget_container-login-form osrFlexItem osrFlexItem__grow ng-scope&quot;]/osr-login[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/osr-login-osr[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;ng-valid ng-scope ng-valid-email ng-valid-required ng-valid-minlength ng-valid-policy ng-dirty ng-valid-parse&quot;]/osr-label[@class=&quot;ng-isolate-scope&quot;]/ng-transclude[1]/osr-password-box[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-not-empty&quot;]/div[@class=&quot;ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-dirty ng-valid-parse&quot;]/div[@class=&quot;osr-text-box&quot;]/input[@class=&quot;osr-text-box__input ng-untouched ng-valid ng-valid-required ng-valid-minlength ng-valid-policy ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>6528acdf-a784-4a57-b229-6002a293d19f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='model.Password']</value>
      <webElementGuid>84b0b0a6-b03f-435f-bb44-43be262bb2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/div/osr-login-osr/form/osr-label/ng-transclude/osr-password-box/div/div/input</value>
      <webElementGuid>85773aa0-5829-414b-bf81-1c663b9b761e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>92ef7cb6-30d0-4d37-8c70-b575a169cd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'model.Password']</value>
      <webElementGuid>b7996579-52f0-4144-b9a0-6849e3f8f62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
