<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_model.Password</name>
   <tag></tag>
   <elementGuidId>b81e9ee6-ffd0-4b9d-a6b2-d38679adba74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='model.Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;model.Password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>920c179b-28da-451e-a185-95c03f98e0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>77986eed-7230-48d2-9724-254a8550630f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ vm.showPassword ? 'text' : 'password' }}</value>
      <webElementGuid>48c52e2d-ab3e-4ecc-aa31-481d28cabca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model.Password</value>
      <webElementGuid>58d57eb3-ec55-4dbf-a68a-31a64cc1e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osr-text-box__input ng-pristine ng-valid ng-empty ng-valid-required ng-valid-minlength ng-valid-policy ng-touched</value>
      <webElementGuid>b2b16eb8-f82a-4a5d-ab35-e922547b4fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.ngModel</value>
      <webElementGuid>1b54b802-9098-4044-be7e-1687891863ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.onChange()</value>
      <webElementGuid>5fb6810e-223a-46f3-a289-ba699b6f2a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>vm.required</value>
      <webElementGuid>63c41493-1868-4c52-8b04-2ccc48a405ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.ngDisabled</value>
      <webElementGuid>2aaec709-220f-4d11-aca8-846814c459ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8406844e-670e-499e-a410-ce725a6ae31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f7e7fcf-5eb9-4618-8aeb-f61b6b3e1912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-autocomplete</name>
      <type>Main</type>
      <value>{{vm.autocomplete == false ? 'off' : ''}}</value>
      <webElementGuid>e3903ce1-5c4e-4191-8e87-eadc1a5c2dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__single_spa_angular_1&quot;)/ui-view[@class=&quot;ultimate ng-scope&quot;]/div[@id=&quot;fullscreen-root-container&quot;]/div[@class=&quot;login osrFlexItem&quot;]/div[@class=&quot;osrFlex&quot;]/div[@class=&quot;widget widget_container-login-form osrFlexItem osrFlexItem__grow ng-scope&quot;]/osr-login[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/osr-login-osr[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;ng-pristine ng-valid ng-scope ng-valid-email ng-valid-required ng-valid-minlength ng-valid-policy&quot;]/osr-label[@class=&quot;ng-isolate-scope&quot;]/ng-transclude[1]/osr-password-box[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope ng-empty&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-required ng-valid-minlength ng-valid-policy&quot;]/div[@class=&quot;osr-text-box&quot;]/input[@class=&quot;osr-text-box__input ng-pristine ng-valid ng-empty ng-valid-required ng-valid-minlength ng-valid-policy ng-touched&quot;]</value>
      <webElementGuid>87f91b4c-04f5-468c-b2cb-f306dff00aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='model.Password']</value>
      <webElementGuid>0fadc87a-54a0-44ce-aeb3-c62366686a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fullscreen-root-container']/div/div/div[2]/osr-login/div/osr-login-osr/form/osr-label/ng-transclude/osr-password-box/div/div/input</value>
      <webElementGuid>400a5841-fc9f-470b-8a19-490a7bf07c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ca71d19c-e76a-4775-9d73-63cc0ee8b2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'model.Password']</value>
      <webElementGuid>8475f320-6ea7-4ce6-9324-34c79d18e7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
